In [16]:
import tensorflow as tf
import numpy as np

In [5]:
zerod_tensor = tf.constant(5)
zerod_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [7]:
oned_tensor = tf.constant([1, 2, 3, 4, 5])
oned_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [10]:
twod_tensor = tf.constant(
    [
    [1, 2, 3, 4,5],
    [6, 7, 8, 9, 10]
    ]
)
twod_tensor

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)>

In [11]:
threed_tensor = tf.constant(
    [
    [[1, 2, 3, 4,5],
    [6, 7, 8, 9, 10]],
    [[11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]],
    [[21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]]
    ]
)
threed_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]], dtype=int32)>

In [13]:
print(zerod_tensor.shape, oned_tensor.shape, twod_tensor.shape, threed_tensor.shape)

() (5,) (2, 5) (3, 2, 5)


In [15]:
one_d_float = tf.constant([1.4, 2.2, 3.7, 4.9], dtype=tf.float32)
one_d_int = tf.cast(one_d_float, dtype=tf.int32)
one_d_int

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [18]:
# np array to tensor
nparr = np.array([1, 2, 3, 4])
tsr = tf.convert_to_tensor(nparr)
tsr

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [20]:
# identity Matrix
eye_tensor = tf.eye(num_rows=3, num_columns=3)
eye_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [29]:
# batch of Identity matrix
batch_eye_tensor = tf.eye(num_rows=5, batch_shape=(3,))
batch_eye_tensor

<tf.Tensor: shape=(3, 5, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)>

In [32]:
var = tf.fill([3, 3], value=11) # shape, value to fill in the shape
var


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]], dtype=int32)>

In [34]:
ones = tf.ones([5, 4]) # Ones with the shape of given matrix
ones 

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [35]:
oneasvar = tf.ones_like(var) # one will be filles in the shape of Var
oneasvar

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
# similar as above, tf.zeros() and tf.zeros_like()

In [38]:
# Rank of a Matrix
'''
Rank of a matrix is the number of linearly independent rows and cols
Ex: a = [[1, 2]
        [3, 6]] 
    Rank of a is : 1 as row 2 is a multiple of row 1
    
'''

rank1 = tf.constant([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 4]])
rank2 = tf.constant([[1,2, 3, 4], [2, 3, 6, 8], [9,  11, 12, 13]])

rank1 = tf.rank(rank1)
rank2 = tf.rank(rank2)
print(rank1, rank2)

tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32)


In [39]:
# Random number generator

randomNum = tf.random.normal([3, 2],mean=0, stddev=1, dtype=tf.float32)
randomNum

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3613545 ,  0.90912664],
       [-1.6975542 ,  1.37452   ],
       [-0.5912331 ,  0.05310647]], dtype=float32)>

In [41]:
randomNum = tf.random.uniform([3, 3], minval = 1, maxval = 10)
randomNum

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[5.0993304, 5.2884083, 2.7557   ],
       [8.826351 , 6.260937 , 7.4880686],
       [5.25667  , 4.1126103, 2.11206  ]], dtype=float32)>