In [1]:
import tensorflow as tf
import numpy as np

In [2]:
zerod_tensor = tf.constant(5)
zerod_tensor

2024-12-22 17:27:26.138981: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3 Pro
2024-12-22 17:27:26.139006: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 18.00 GB
2024-12-22 17:27:26.139012: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 6.00 GB
2024-12-22 17:27:26.139200: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-12-22 17:27:26.139216: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [3]:
oned_tensor = tf.constant([1, 2, 3, 4, 5])
oned_tensor

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [4]:
twod_tensor = tf.constant(
    [
    [1, 2, 3, 4,5],
    [6, 7, 8, 9, 10]
    ]
)
twod_tensor

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)>

In [5]:
threed_tensor = tf.constant(
    [
    [[1, 2, 3, 4,5],
    [6, 7, 8, 9, 10]],
    [[11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]],
    [[21, 22, 23, 24, 25],
    [26, 27, 28, 29, 30]]
    ]
)
threed_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]], dtype=int32)>

In [6]:
print(zerod_tensor.shape, oned_tensor.shape, twod_tensor.shape, threed_tensor.shape)

() (5,) (2, 5) (3, 2, 5)


In [7]:
one_d_float = tf.constant([1.4, 2.2, 3.7, 4.9], dtype=tf.float32)
one_d_int = tf.cast(one_d_float, dtype=tf.int32)
one_d_int

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [8]:
# np array to tensor
nparr = np.array([1, 2, 3, 4])
tsr = tf.convert_to_tensor(nparr)
tsr

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [9]:
# identity Matrix
eye_tensor = tf.eye(num_rows=3, num_columns=3)
eye_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [10]:
# batch of Identity matrix
batch_eye_tensor = tf.eye(num_rows=5, batch_shape=(3,))
batch_eye_tensor

<tf.Tensor: shape=(3, 5, 5), dtype=float32, numpy=
array([[[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]],

       [[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]], dtype=float32)>

In [11]:
var = tf.fill([3, 3], value=11) # shape, value to fill in the shape
var


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]], dtype=int32)>

In [12]:
ones = tf.ones([5, 4]) # Ones with the shape of given matrix
ones 

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [13]:
oneasvar = tf.ones_like(var) # one will be filles in the shape of Var
oneasvar

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [14]:
# similar as above, tf.zeros() and tf.zeros_like()

In [15]:
# Rank of a Matrix
'''
Rank of a matrix is the number of linearly independent rows and cols
Ex: a = [[1, 2]
        [3, 6]] 
    Rank of a is : 1 as row 2 is a multiple of row 1
    
'''

rank1 = tf.constant([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 4]])
rank2 = tf.constant([[1,2, 3, 4], [2, 3, 6, 8], [9,  11, 12, 13]])

rank1 = tf.rank(rank1)
rank2 = tf.rank(rank2)
print(rank1, rank2)

tf.Tensor(2, shape=(), dtype=int32) tf.Tensor(2, shape=(), dtype=int32)


In [16]:
# Random number generator

randomNum = tf.random.normal([3, 2],mean=0, stddev=1, dtype=tf.float32)
randomNum

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.51802546,  0.76889026],
       [ 0.408056  ,  1.4575773 ],
       [ 0.5271901 , -1.1638874 ]], dtype=float32)>

In [17]:
randomNum = tf.random.uniform([3, 3], minval = 1, maxval = 10)
randomNum

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[5.1499977, 4.9791126, 9.379074 ],
       [9.092012 , 8.943333 , 5.89573  ],
       [6.190186 , 4.4512777, 3.6784892]], dtype=float32)>

In [25]:
#slicing

two_d = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

two_d[ 1:3, 1:3] # row, col
# : this mean pick all indices
# ... this also means picking all indices

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 6],
       [8, 9]], dtype=int32)>

In [29]:
three_d = tf.constant([
    [
    [1, 2, 3],
    [4, 5, 6]
    ],
    [
    [7, 8, 9],
    [10, 11, 12]
    ]
    ])

three_d[0, :, :] # row, col, channel

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [30]:
# Broadcasting, it takes out similar elements to the original shape as required for the operation

c1 = tf.constant([1, 4, 8, 3, 7, 11])
c2 = tf.constant([10])
c1 / c2 # c2 broadcasted itself in shape of c1

<tf.Tensor: shape=(6,), dtype=float64, numpy=array([0.1, 0.4, 0.8, 0.3, 0.7, 1.1])>

In [36]:
two_d = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(tf.reduce_sum(two_d), tf.reduce_max(two_d)) # sum and max
print(tf.reduce_sum(two_d, axis=0), tf.reduce_max(two_d, axis=0)) # reducing to col sum
print(tf.reduce_sum(two_d, axis=1), tf.reduce_max(two_d, axis=1)) # reducing to row sum


tf.Tensor(78, shape=(), dtype=int32) tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor([22 26 30], shape=(3,), dtype=int32) tf.Tensor([10 11 12], shape=(3,), dtype=int32)
tf.Tensor([ 6 15 24 33], shape=(4,), dtype=int32) tf.Tensor([ 3  6  9 12], shape=(4,), dtype=int32)


In [37]:
x1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

x2 = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [2, 3, 7]
])

tf.matmul(x1, x2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[15, 21, 36],
       [36, 51, 84]], dtype=int32)>

In [38]:
x1@x2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[15, 21, 36],
       [36, 51, 84]], dtype=int32)>

In [40]:
# x1 * x2 # this is element wise multiplication