In [1]:
import numpy as np
import tensorflow as tf

In [9]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 14, 16]
])

b = np.array([
    [1, 2, 3, -1],
    [5, 6, 7, -2],
    [9, 10, 11, -3],
    [13, 14, 16, -4]
])

np.matmul(a, b)

array([[  90,  100,  114,  -30],
       [ 202,  228,  262,  -70],
       [ 314,  356,  410, -110],
       [ 417,  474,  547, -147]])

In [10]:
np.einsum("ij,jk -> ik", a,b)

array([[  90,  100,  114,  -30],
       [ 202,  228,  262,  -70],
       [ 314,  356,  410, -110],
       [ 417,  474,  547, -147]])

In [12]:
np.einsum("ij,ij -> ij", a, b)

array([[  1,   4,   9,  -4],
       [ 25,  36,  49, -16],
       [ 81, 100, 121, -36],
       [169, 196, 224, -64]])

In [13]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 14, 16]
])

print("Transpose: ", a.T)

Transpose:  [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 14]
 [ 4  8 12 16]]


In [14]:
np.einsum("ij -> ji", a)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 14],
       [ 4,  8, 12, 16]])

In [20]:
# a -> (2, 3, 4)
# b -> (2, 4, 5)

# c -> (2, 3, 5)

a = np.array([
    [[1, 1, 1, 0],
    [2, 2, 2, 0],
    [1, 1, 1, 0]],
    [[3, 3, 3, 0],
     [4, 4, 4, 0],
     [7, 7, 7, 0]]
])

b = np.array([
    [[-1, 1, 1],
    [-2, 2, 2],
    [-1, 1, 1],
    [-7, 7, 7]],
    [[-3, 3, 3],
     [-4, 4, 4],
     [-7, 7, 7],
     [5, 6, 5]]
])

print(a.shape, b.shape)
print(np.matmul(a, b))

(2, 3, 4) (2, 4, 3)
[[[ -4   4   4]
  [ -8   8   8]
  [ -4   4   4]]

 [[-42  42  42]
  [-56  56  56]
  [-98  98  98]]]


In [22]:
np.einsum("ijk,ikp -> ijp", a, b)

array([[[ -4,   4,   4],
        [ -8,   8,   8],
        [ -4,   4,   4]],

       [[-42,  42,  42],
        [-56,  56,  56],
        [-98,  98,  98]]])

In [24]:
a = np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

np.sum(a, axis=0), np.sum(a, axis=1)

(array([6, 6, 6]), array([3, 6, 9]))

In [32]:
a = np.array([
    [[1, 1, 1, 0],
    [2, 2, 2, 0],
    [1, 1, 1, 0]],
    [[3, 3, 3, 0],
     [4, 4, 4, 0],
     [7, 7, 7, 0]]
])

print("Original Shape: ", a.shape)
aexp = tf.expand_dims(a, axis=0)
print("Expanded Shape: ",aexp.shape)

Original Shape:  (2, 3, 4)
Expanded Shape:  (1, 2, 3, 4)


In [33]:
print(tf.squeeze(aexp, axis=0).shape)

(2, 3, 4)
