In [1]:
import torch
import numpy as np

In [2]:
scalar = torch.tensor(1)
scalar, scalar.item(), scalar.ndim

(tensor(1), 1, 0)

In [3]:
vector = torch.tensor([1, 2, 3, 4, 5])
vector, vector.ndim, vector.shape

(tensor([1, 2, 3, 4, 5]), 1, torch.Size([5]))

In [4]:
matrix = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])
matrix, matrix.ndim, matrix.shape

(tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]),
 2,
 torch.Size([2, 4]))

In [5]:
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
tensor, tensor.ndim, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 3,
 torch.Size([1, 3, 3]))

In [6]:
randomMat = torch.rand(4, 2, 4)
randomMat, randomMat.ndim, randomMat.shape

(tensor([[[0.2311, 0.0027, 0.8436, 0.4949],
          [0.2336, 0.4721, 0.9210, 0.3112]],
 
         [[0.4355, 0.3583, 0.9970, 0.3899],
          [0.5103, 0.0993, 0.3415, 0.4887]],
 
         [[0.2627, 0.2915, 0.9575, 0.2548],
          [0.3344, 0.1296, 0.8317, 0.3870]],
 
         [[0.2078, 0.1831, 0.3157, 0.2752],
          [0.7991, 0.6947, 0.5625, 0.2490]]]),
 3,
 torch.Size([4, 2, 4]))

In [7]:
image = torch.rand(size = (128, 128, 3))
# image
# torch.ones, torch.zeros

In [8]:
torch.range(0, 10, 0.1), torch.arange(0, 10, 1)

<ipython-input-8-6fbb8e8ee927>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10, 0.1), torch.arange(0, 10, 1)


(tensor([ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,  0.7000,
          0.8000,  0.9000,  1.0000,  1.1000,  1.2000,  1.3000,  1.4000,  1.5000,
          1.6000,  1.7000,  1.8000,  1.9000,  2.0000,  2.1000,  2.2000,  2.3000,
          2.4000,  2.5000,  2.6000,  2.7000,  2.8000,  2.9000,  3.0000,  3.1000,
          3.2000,  3.3000,  3.4000,  3.5000,  3.6000,  3.7000,  3.8000,  3.9000,
          4.0000,  4.1000,  4.2000,  4.3000,  4.4000,  4.5000,  4.6000,  4.7000,
          4.8000,  4.9000,  5.0000,  5.1000,  5.2000,  5.3000,  5.4000,  5.5000,
          5.6000,  5.7000,  5.8000,  5.9000,  6.0000,  6.1000,  6.2000,  6.3000,
          6.4000,  6.5000,  6.6000,  6.7000,  6.8000,  6.9000,  7.0000,  7.1000,
          7.2000,  7.3000,  7.4000,  7.5000,  7.6000,  7.7000,  7.8000,  7.9000,
          8.0000,  8.1000,  8.2000,  8.3000,  8.4000,  8.5000,  8.6000,  8.7000,
          8.8000,  8.9000,  9.0000,  9.1000,  9.2000,  9.3000,  9.4000,  9.5000,
          9.6000,  9.7000,  

In [9]:
# tensor.torch.zeros_like, tensor.ones_like


In [10]:
tensor = torch.tensor([1, 2, 3, 4, 5])
tensor + 10, tensor - 10, tensor * 10, tensor / 10

(tensor([11, 12, 13, 14, 15]),
 tensor([-9, -8, -7, -6, -5]),
 tensor([10, 20, 30, 40, 50]),
 tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000]))

In [11]:
tensor.add(10), tensor.sub(10), tensor.mul(10), tensor.div(10)

(tensor([11, 12, 13, 14, 15]),
 tensor([-9, -8, -7, -6, -5]),
 tensor([10, 20, 30, 40, 50]),
 tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000]))

In [12]:
tensor * tensor

tensor([ 1,  4,  9, 16, 25])

In [13]:
torch.matmul(tensor, tensor)

tensor(55)

In [14]:
%%time
ans = 0
for i in range(4):
    ans += tensor[i] * tensor[i]

CPU times: user 1.1 ms, sys: 0 ns, total: 1.1 ms
Wall time: 2.1 ms


In [15]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 102 µs, sys: 0 ns, total: 102 µs
Wall time: 107 µs


tensor(55)

In [16]:
tensor @ tensor

tensor(55)

## Remeber this

**For matrix multiplication to work, the last dimension of the first tensor and the second-to-last dimension of the second tensor must match. That means, for torch.matmul(A, B), the shape of A should be (X, Y, Z) and the shape of B should be (X, Z, W), where Z is the same in both tensors.**

torch.matmul is same as torch.mm

http://matrixmultiplication.xyz/


In [17]:
torch.matmul(torch.rand((2, 3, 2, 1)), torch.rand((2, 3, 1, 1)))

tensor([[[[0.1223],
          [0.2030]],

         [[0.1985],
          [0.6147]],

         [[0.2413],
          [0.2007]]],


        [[[0.1884],
          [0.1415]],

         [[0.5905],
          [0.0399]],

         [[0.6612],
          [0.6182]]]])

In [18]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)
torch.matmul(a, b.T)

tensor([[0.8231, 0.5629],
        [0.7775, 0.9529]])

In [19]:
a = torch.rand(2, 3, 2)
b = torch.rand(2, 2, 1)
torch.matmul(a, b)

tensor([[[0.1524],
         [0.3068],
         [0.0699]],

        [[0.6626],
         [0.3871],
         [0.5386]]])

In [20]:
a = torch.rand(2, 2, 3, 5)
b = torch.rand(2, 2, 5, 1)
torch.matmul(a, b)

tensor([[[[1.6722],
          [1.7144],
          [2.1908]],

         [[1.1786],
          [0.3579],
          [0.6218]]],


        [[[0.5044],
          [1.4319],
          [1.1872]],

         [[1.5944],
          [1.2173],
          [1.3886]]]])

In [21]:
tensor1 = torch.rand((2, 3, 2, 1))
tensor2 = torch.rand((2, 2, 3, 1))

# Permute the tensors to align inner dimensions
tensor1_permuted = tensor1.permute(0, 1, 2, 3)  # (2, 3, 2, 1)
tensor2_permuted = tensor2.permute(0, 2, 3, 1)  # (2, 3, 1, 2)
torch.matmul(tensor1_permuted, tensor2_permuted)

tensor([[[[0.0613, 0.0141],
          [0.0757, 0.0174]],

         [[0.2217, 0.1418],
          [0.1526, 0.0976]],

         [[0.6882, 0.6394],
          [0.7852, 0.7296]]],


        [[[0.0727, 0.0807],
          [0.2996, 0.3326]],

         [[0.1497, 0.2117],
          [0.5601, 0.7919]],

         [[0.0701, 0.0567],
          [0.1362, 0.1101]]]])

In [22]:
x = torch.arange(0, 1000, 10)
torch.min(x), x.min(), torch.max(x), x.max()

(tensor(0), tensor(0), tensor(990), tensor(990))

We cannot find mean with int or long type, it should be float

In [23]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(495.), tensor(495.))

In [24]:
x.argmin(), x.argmax()

(tensor(0), tensor(99))

Reshape: rehsapes the input tensor

View:returns a view of the input tensor of certain shape but keeps the same memory as original tensor

Stacking: hstack, vstack

Squeeze: removes all 1 - dimensions of tensor

Un-Squeeze - add 1 dimension of tensor

permute - returns the view of input tensor with dimensions permuted(swapped)

In [25]:
x = torch.rand(1, 20)
x

tensor([[0.0970, 0.4488, 0.8927, 0.5028, 0.8658, 0.7555, 0.1616, 0.0774, 0.8527,
         0.5989, 0.1813, 0.9048, 0.6539, 0.8744, 0.0612, 0.2013, 0.1654, 0.9616,
         0.2504, 0.5364]])

In [26]:
x.reshape(10, 2)
# at the end total number of elements should be same

tensor([[0.0970, 0.4488],
        [0.8927, 0.5028],
        [0.8658, 0.7555],
        [0.1616, 0.0774],
        [0.8527, 0.5989],
        [0.1813, 0.9048],
        [0.6539, 0.8744],
        [0.0612, 0.2013],
        [0.1654, 0.9616],
        [0.2504, 0.5364]])

In [27]:
z = x.view(4, 5)
z

tensor([[0.0970, 0.4488, 0.8927, 0.5028, 0.8658],
        [0.7555, 0.1616, 0.0774, 0.8527, 0.5989],
        [0.1813, 0.9048, 0.6539, 0.8744, 0.0612],
        [0.2013, 0.1654, 0.9616, 0.2504, 0.5364]])

In [28]:
z[:,0] = 99
z, x
# as z is a view of x, z makes the modificaction at address level so any change in z will effect x directly(only the values, not shapes)

(tensor([[9.9000e+01, 4.4877e-01, 8.9268e-01, 5.0281e-01, 8.6581e-01],
         [9.9000e+01, 1.6162e-01, 7.7388e-02, 8.5274e-01, 5.9887e-01],
         [9.9000e+01, 9.0479e-01, 6.5392e-01, 8.7443e-01, 6.1152e-02],
         [9.9000e+01, 1.6538e-01, 9.6161e-01, 2.5036e-01, 5.3640e-01]]),
 tensor([[9.9000e+01, 4.4877e-01, 8.9268e-01, 5.0281e-01, 8.6581e-01, 9.9000e+01,
          1.6162e-01, 7.7388e-02, 8.5274e-01, 5.9887e-01, 9.9000e+01, 9.0479e-01,
          6.5392e-01, 8.7443e-01, 6.1152e-02, 9.9000e+01, 1.6538e-01, 9.6161e-01,
          2.5036e-01, 5.3640e-01]]))

In [29]:
xstack = torch.rand(2, 2)
print(xstack)
xstack = torch.stack([xstack, xstack], dim = 0)
ystack = torch.stack([xstack, xstack], dim = 1)

xstack, ystack

tensor([[0.3741, 0.9610],
        [0.0885, 0.4510]])


(tensor([[[0.3741, 0.9610],
          [0.0885, 0.4510]],
 
         [[0.3741, 0.9610],
          [0.0885, 0.4510]]]),
 tensor([[[[0.3741, 0.9610],
           [0.0885, 0.4510]],
 
          [[0.3741, 0.9610],
           [0.0885, 0.4510]]],
 
 
         [[[0.3741, 0.9610],
           [0.0885, 0.4510]],
 
          [[0.3741, 0.9610],
           [0.0885, 0.4510]]]]))

In [41]:
tensor = torch.rand(1, 10, 1, 3)
print("Original ", tensor.shape, '\n', tensor)
tensor = torch.squeeze(tensor)
print("After Squeezing ", tensor.shape,'\n', tensor)
tensor = torch.unsqueeze(tensor, dim = 0)
print("After Un-Squeezing ", tensor.shape, '\n', tensor)

Original  torch.Size([1, 10, 1, 3]) 
 tensor([[[[0.1527, 0.4414, 0.9186]],

         [[0.5237, 0.7689, 0.5394]],

         [[0.1362, 0.5239, 0.4502]],

         [[0.2663, 0.4566, 0.9266]],

         [[0.3549, 0.3828, 0.3603]],

         [[0.9705, 0.0999, 0.5730]],

         [[0.5028, 0.7748, 0.6413]],

         [[0.6071, 0.4078, 0.4046]],

         [[0.7401, 0.7774, 0.6934]],

         [[0.2185, 0.8012, 0.4625]]]])
After Squeezing  torch.Size([10, 3]) 
 tensor([[0.1527, 0.4414, 0.9186],
        [0.5237, 0.7689, 0.5394],
        [0.1362, 0.5239, 0.4502],
        [0.2663, 0.4566, 0.9266],
        [0.3549, 0.3828, 0.3603],
        [0.9705, 0.0999, 0.5730],
        [0.5028, 0.7748, 0.6413],
        [0.6071, 0.4078, 0.4046],
        [0.7401, 0.7774, 0.6934],
        [0.2185, 0.8012, 0.4625]])
After Un-Squeezing  torch.Size([1, 10, 3]) 
 tensor([[[0.1527, 0.4414, 0.9186],
         [0.5237, 0.7689, 0.5394],
         [0.1362, 0.5239, 0.4502],
         [0.2663, 0.4566, 0.9266],
         [0.3549

In [43]:
image = torch.rand(224, 224, 3)
imagePerm1 = torch.permute(image, (2, 0, 1))
imagePerm2 = torch.permute(image, (1, 2, 0))

image.shape, imagePerm1.shape, imagePerm2.shape

(torch.Size([224, 224, 3]),
 torch.Size([3, 224, 224]),
 torch.Size([224, 3, 224]))

In [46]:
npArr = np.arange(1.0, 10)
tensor = torch.from_numpy(npArr)
npArr, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [58]:
tenArr = torch.arange(1.0, 10)
npArr = tenArr.numpy()
tenArr, npArr

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32))

In [59]:
torch.rand(3, 3)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])

In [60]:
torch.manual_seed(42)
torch.rand(3, 3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

In [61]:
torch.rand(3, 3)
# In Colab when you use random_seed, call it everytime wheenver you use it

tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

Running Object on GPU's

In [62]:
torch.cuda.is_available()

False

In [63]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [64]:
torch.cuda.device_count()

0